name: 'Mirror'

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *"

jobs:
  mirror:
    name: Automatic Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        
      - name: Mirroring
        run: |
          git remote add --mirror=fetch mirror "https://github.com/OCA/stock-logistics-workflow.git"
          git fetch mirror +refs/heads/*:refs/remotes/origin/*
          git push --force --mirror --prune origin
